import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { PLUGIN_AGENT_ROLES, renderAgent } from "../../scripts/build-plugin.js";
import { CEILINGS } from "../../src/schemas/budgets.js";
import { READ_ONLY_ROLES } from "../../src/schemas/roles.js";
import { toolsForRole } from "../../src/sessions/guard.js";
import { loadPromptSet, resolveAssignment } from "../../src/sessions/prompts.js";

/**
 * T-112 — the vendored role subagents (S-7, S-3′, SEC-2).
 *
 * `agents/<role>.md` is generated by scripts/build-plugin.ts: the body is the
 * S-7-pinned prompt byte-for-byte, the frontmatter derives from the same
 * sources the SDK backend uses. These tests are the staleness gate (regenerate
 * and compare) and the hash-pin proof (`role@hash` resolves against the body
 * that actually ships) — an edited agent file, an edited prompt, or an edited
 * surface that is not regenerated together fails here.
 */

const ROOT = path.resolve(import.meta.dirname, "..", "..");
const set = loadPromptSet();

const agentFile = (role: string): string => readFileSync(path.join(ROOT, "agents", `${role}.md`), "utf8");

/** The body is everything after the closing frontmatter fence. */
function bodyOf(content: string): string {
  const close = content.indexOf("\n---\n", "---".length);
  expect(close).toBeGreaterThan(0);
  return content.slice(close + "\n---\n".length);
}

function frontmatterOf(content: string): Map<string, string> {
  const close = content.indexOf("\n---\n", "---".length);
  const entries = content
    .slice("---\n".length, close)
    .split("\n")
    .map((line) => {
      const sep = line.indexOf(": ");
      return [line.slice(0, sep), line.slice(sep + 2)] as const;
    });
  return new Map(entries);
}

describe("T-112 vendored subagents (S-7 hash pin)", () => {
  it("agents/ is a closed set: exactly the four plan-named roles", () => {
    expect(readdirSync(path.join(ROOT, "agents")).sort()).toEqual(
      [...PLUGIN_AGENT_ROLES].map((r) => `${r}.md`).sort(),
    );
  });

  it("staleness: every committed agent file byte-equals a fresh render", () => {
    for (const role of PLUGIN_AGENT_ROLES) {
      expect(agentFile(role), `agents/${role}.md is stale — run \`npm run plugin\``).toBe(
        renderAgent(role, set.prompts[role]),
      );
    }
  });

  it("the shipped body IS the pinned prompt: sha256(body) matches prompts/manifest.json and role@hash resolves", () => {
    for (const role of PLUGIN_AGENT_ROLES) {
      const body = bodyOf(agentFile(role));
      const hash = createHash("sha256").update(body).digest("hex");
      expect(hash, role).toBe(set.hashes[role]);
      expect(resolveAssignment(`${role}@${hash}`, set).role).toBe(role);
    }
  });
});

describe("T-112 role surfaces in frontmatter (S-3′)", () => {
  it("tools mirror toolsForRole exactly — the SDK allowlist and the frontmatter are one truth", () => {
    for (const role of PLUGIN_AGENT_ROLES) {
      const fm = frontmatterOf(agentFile(role));
      expect(fm.get("tools"), role).toBe(toolsForRole(role, []).join(", "));
      expect(fm.get("name"), role).toBe(`detent-${role}`);
      expect(fm.get("description"), role).toMatch(/^"Detent .+"$/);
    }
  });

  it("read-only roles run permissionMode plan; implement runs default (S-1)", () => {
    for (const role of PLUGIN_AGENT_ROLES) {
      const fm = frontmatterOf(agentFile(role));
      expect(fm.get("permissionMode"), role).toBe(READ_ONLY_ROLES.has(role) ? "plan" : "default");
    }
  });

  it("every role caps turns at the X-1 turns_per_stage default and disallows nested Task spawns (D-28)", () => {
    for (const role of PLUGIN_AGENT_ROLES) {
      const fm = frontmatterOf(agentFile(role));
      expect(fm.get("maxTurns"), role).toBe(String(CEILINGS.turns_per_stage.default));
      expect(fm.get("disallowedTools"), role).toBe("Task");
    }
  });

  it("research ships the domain-less web surface while PRDR-062 is open — narrower, never wider", () => {
    const fm = frontmatterOf(agentFile("research"));
    expect(fm.get("tools")).toContain("WebSearch");
    expect(fm.get("tools")).not.toContain("WebFetch");
  });
});
