/**
 * T-018 — regenerates the two derived documents:
 *   tests/oracle/PARITY.md   the oracle parity report
 *   docs/critical-path.md    the critical path, computed from the plan's deps
 *
 * Both are checked in and diffed by CI, so an edit that reshapes the dependency
 * graph or moves a test's closing ticket fails the build rather than silently
 * rotting a hand-written diagram.
 *
 * Usage: tsx scripts/parity.ts [--check]
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { PARITY, ORACLE_TEST_COUNT, LANDED_THROUGH, milestoneOf, statusOf } from "../tests/oracle/parity.map.js";

const ROOT = path.resolve(import.meta.dirname, "..");
const PLAN = path.join(ROOT, "docs/implementation-plan.md");

/* ---- parity report --------------------------------------------------------- */

export function renderParity(): string {
  const rows = [...PARITY].sort((a, b) => a.oracle.localeCompare(b.oracle));
  const tally = new Map<string, number>();
  for (const e of rows) tally.set(statusOf(e), (tally.get(statusOf(e)) ?? 0) + 1);

  const lines = [
    "# Oracle parity report",
    "",
    "Generated by `scripts/parity.ts` — do not edit by hand; CI regenerates and diffs it.",
    "",
    `The Python reference (v0.1.3) has **${ORACLE_TEST_COUNT}** tests. Every one appears below exactly`,
    "once with the ticket that closes it. `green` means the port exists and cites that ticket; a",
    "pending row is labelled by the milestone that will close it. Both are derived, never asserted",
    "separately, so the table cannot drift from the suite. Each milestone exit asserts its own",
    `threshold (R-2) rather than one global count. Landed through **${LANDED_THROUGH}**.`,
    "",
    "| Status | Count |",
    "|---|---:|",
    ...["green", "pending-M1", "pending-M2", "pending-later"].map(
      (s) => `| ${s} | ${tally.get(s) ?? 0} |`,
    ),
    `| **total** | **${rows.length}** |`,
    "",
    "| Oracle test | Status | Closes at | TypeScript home | Note |",
    "|---|---|---|---|---|",
    ...rows.map(
      (e) =>
        `| \`${e.oracle}\` | ${statusOf(e)} | ${e.ticket} (${milestoneOf(e.ticket)}) | ${e.ts ? `\`${e.ts}\`` : "—"} | ${e.note ?? ""} |`,
    ),
    "",
  ];
  return lines.join("\n");
}

/* ---- critical path --------------------------------------------------------- */

interface Ticket { readonly id: string; readonly deps: readonly string[] }

export function parsePlan(planText: string): Ticket[] {
  const ids: string[] = [];
  const raw: Array<[string, string]> = [];
  for (const line of planText.split("\n")) {
    const m = /^\*\*(T-\d{3}) · .+? \[.+?\] — deps: (.*)$/.exec(line);
    if (m === null) continue;
    ids.push(m[1]!);
    raw.push([m[1]!, m[2]!]);
  }
  const num = (id: string) => Number(id.slice(2));
  const m3 = ids.filter((id) => num(id) >= 60 && num(id) < 80);

  return raw.map(([id, spec]) => {
    const text = spec.replace(/\*\*/g, "").split(";")[0]!.trim();
    if (text.startsWith("none")) return { id, deps: [] };
    if (text.includes("all M3")) return { id, deps: m3 };
    const deps = new Set<string>();
    for (const part of text.split(",").map((p) => p.trim())) {
      const range = /^T-(\d{3})…T-(\d{3})/.exec(part);
      if (range !== null) {
        const [lo, hi] = [Number(range[1]), Number(range[2])];
        for (const other of ids) if (num(other) >= lo && num(other) <= hi && other !== id) deps.add(other);
        continue;
      }
      const single = /^(T-\d{3})/.exec(part);
      if (single !== null) deps.add(single[1]!);
    }
    return { id, deps: [...deps] };
  });
}

export function longestChain(tickets: readonly Ticket[]): string[] {
  const byId = new Map(tickets.map((t) => [t.id, t]));
  for (const t of tickets) {
    for (const d of t.deps) if (!byId.has(d)) throw new Error(`${t.id} depends on unknown ticket ${d}`);
  }
  const depth = new Map<string, number>();
  const pred = new Map<string, string | null>();

  const solve = (id: string, onPath: readonly string[]): number => {
    if (onPath.includes(id)) throw new Error(`dependency cycle: ${[...onPath, id].join(" -> ")}`);
    const cached = depth.get(id);
    if (cached !== undefined) return cached;
    let best = 0;
    let from: string | null = null;
    /** Ascending id breaks ties, so the output is stable across runs. */
    for (const d of [...byId.get(id)!.deps].sort()) {
      const v = solve(d, [...onPath, id]);
      if (v > best) { best = v; from = d; }
    }
    depth.set(id, best + 1);
    pred.set(id, from);
    return best + 1;
  };
  for (const t of tickets) solve(t.id, []);

  const terminal = [...depth.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0]![0];
  const chain: string[] = [];
  for (let cur: string | null = terminal; cur !== null; cur = pred.get(cur) ?? null) chain.push(cur);
  return chain.reverse();
}

export function renderCriticalPath(tickets: readonly Ticket[]): string {
  const chain = longestChain(tickets);
  return [
    "# Critical path",
    "",
    "Generated by `scripts/parity.ts` — do not edit by hand; CI regenerates and diffs it.",
    "",
    `Longest chain in the dependency graph: **${chain.length}** of ${tickets.length} tickets.`,
    "Every arrow is a real `deps:` edge. Ties break by ascending ticket id.",
    "",
    "```",
    chain.join(" → "),
    "```",
    "",
  ].join("\n");
}

/* ---- entry point ----------------------------------------------------------- */

const OUTPUTS = () => {
  const tickets = parsePlan(readFileSync(PLAN, "utf8"));
  return [
    { file: path.join(ROOT, "tests/oracle/PARITY.md"), content: renderParity() },
    { file: path.join(ROOT, "docs/critical-path.md"), content: renderCriticalPath(tickets) },
  ];
};

if (process.argv[1] === new URL(import.meta.url).pathname) {
  const check = process.argv.includes("--check");
  let drift = false;
  for (const { file, content } of OUTPUTS()) {
    const current = (() => { try { return readFileSync(file, "utf8"); } catch { return null; } })();
    if (current === content) continue;
    drift = true;
    if (check) console.error(`drift: ${path.relative(ROOT, file)} is stale — run \`npm run parity\``);
    else { writeFileSync(file, content); console.log(`wrote ${path.relative(ROOT, file)}`); }
  }
  if (check && drift) process.exit(1);
}

export { OUTPUTS };
